# Generated by Django 5.1.4 on 2026-05-12 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(max_length=160, verbose_name='Entreprise')),
                ('contact_name', models.CharField(blank=True, max_length=160, verbose_name='Contact')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=40)),
                ('password_hash', models.CharField(blank=True, editable=False, max_length=256)),
                ('temporary_password', models.CharField(blank=True, help_text='Écrivez un nouveau mot de passe ici puis enregistrez. Il sera sécurisé automatiquement.', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Client professionnel',
                'verbose_name_plural': 'Clients professionnels',
                'ordering': ['company_name'],
            },
        ),
        migrations.AddField(
            model_name='blogpost',
            name='external_image',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='customer_type',
            field=models.CharField(choices=[('particulier', 'Particulier'), ('professionnel', 'Professionnel')], default='particulier', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_issue_note',
            field=models.TextField(blank=True, verbose_name='Note livraison/refus'),
        ),
        migrations.AddField(
            model_name='product',
            name='professional_only',
            field=models.BooleanField(default=False, verbose_name='Réservé aux professionnels'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'En attente'), ('paid', 'Payée'), ('failed', 'Échec'), ('refunded', 'Remboursée'), ('cash', 'Paiement livraison/retrait')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('received', 'Commande reçue'), ('preparing', 'Préparation'), ('ready', 'Prête'), ('delivered', 'Livrée'), ('not_received', 'Client non livré / produit non reçu'), ('refused', 'Produit refusé par le client'), ('cancelled', 'Annulée'), ('refunded', 'Remboursée')], default='received', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='professional_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.professionalclient'),
        ),
    ]
