# Generated by Django 5.1.4 on 2026-07-16 12:42

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_order_email_flags'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiningTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=20, unique=True, verbose_name='Table')),
                ('seats', models.PositiveIntegerField(default=2, verbose_name='Couverts')),
                ('x', models.PositiveSmallIntegerField(default=10, verbose_name='Position X')),
                ('y', models.PositiveSmallIntegerField(default=10, verbose_name='Position Y')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Table salle',
                'verbose_name_plural': 'Tables salle',
                'ordering': ['label'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('supplier', models.CharField(max_length=160, verbose_name='Fournisseur')),
                ('reference', models.CharField(blank=True, max_length=80)),
                ('expected_date', models.DateField(blank=True, null=True, verbose_name='Date prévue')),
                ('received_date', models.DateField(blank=True, null=True, verbose_name='Date reçue')),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('ordered', 'Commandée'), ('received', 'Reçue'), ('cancelled', 'Annulée')], default='draft', max_length=20)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Commande fournisseur',
                'verbose_name_plural': 'Commandes fournisseurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=140, verbose_name='Nom')),
                ('username', models.CharField(max_length=80, unique=True, verbose_name='Nom utilisateur')),
                ('role', models.CharField(blank=True, default='Équipe', max_length=80)),
                ('password_hash', models.CharField(blank=True, editable=False, max_length=256)),
                ('temporary_password', models.CharField(blank=True, help_text='Écrivez un nouveau mot de passe ici puis enregistrez.', max_length=80)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Employé',
                'verbose_name_plural': 'Employés',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Article')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=8)),
                ('unit', models.CharField(default='pièce', max_length=30)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('received_quantity', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='shop.purchaseorder')),
            ],
            options={
                'verbose_name': 'Article fournisseur',
                'verbose_name_plural': 'Articles fournisseurs',
            },
        ),
        migrations.CreateModel(
            name='StaffShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('checked_in', 'Présent'), ('break', 'En pause'), ('checked_out', 'Sorti')], default='checked_in', max_length=20)),
                ('check_in_at', models.DateTimeField(blank=True, null=True)),
                ('break_started_at', models.DateTimeField(blank=True, null=True)),
                ('break_ended_at', models.DateTimeField(blank=True, null=True)),
                ('check_out_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='shop.staffmember')),
            ],
            options={
                'verbose_name': 'Pointage équipe',
                'verbose_name_plural': 'Pointages équipe',
                'ordering': ['-check_in_at', '-created_at'],
            },
        ),
    ]
