# Generated by Django 5.1.4 on 2026-07-27 20:37

from datetime import time

from django.db import migrations, models


def seed_verified_restaurant_operations(apps, schema_editor):
    OpeningPeriod = apps.get_model('shop', 'OpeningPeriod')
    SiteConfiguration = apps.get_model('shop', 'SiteConfiguration')
    Category = apps.get_model('shop', 'Category')
    Product = apps.get_model('shop', 'Product')

    SiteConfiguration.objects.get_or_create(pk=1)
    for weekday in range(1, 6):
        OpeningPeriod.objects.get_or_create(
            weekday=weekday,
            opens_at=time(11, 30),
            closes_at=time(14, 30),
        )
        OpeningPeriod.objects.get_or_create(
            weekday=weekday,
            opens_at=time(18, 30),
            closes_at=time(22, 30),
        )

    Category.objects.filter(name='Nos Pizza').update(name='Nos pizzas')
    Category.objects.filter(name='Nos Pastas').update(name='Nos pâtes')
    Product.objects.filter(name='La Quattro fromaggi').update(name='La Quattro Formaggi')
    Product.objects.filter(name='Supplément buffala').update(name='Supplément bufala')
    Product.objects.filter(badge__iexact='Végétarien').update(is_vegetarian=True)
    Product.objects.filter(badge__iexact='Épicée').update(is_spicy=True)
    Product.objects.filter(badge__iexact='Signature').update(is_signature=True)


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_loyaltyredemption'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExceptionalClosure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(unique=True)),
                ('reason', models.CharField(blank=True, max_length=180)),
                ('is_closed', models.BooleanField(default=True, verbose_name='Fermé toute la journée')),
                ('opens_at', models.TimeField(blank=True, null=True, verbose_name='Ouverture exceptionnelle')),
                ('closes_at', models.TimeField(blank=True, null=True, verbose_name='Fermeture exceptionnelle')),
            ],
            options={
                'verbose_name': 'Fermeture exceptionnelle',
                'verbose_name_plural': 'Fermetures exceptionnelles',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('restaurant_name', models.CharField(default='Pizza Vitti', max_length=120)),
                ('hero_title', models.CharField(default='Pizza italienne artisanale au cœur de Bordeaux', max_length=180)),
                ('hero_description', models.TextField(default='Des pizzas généreuses préparées avec des produits italiens soigneusement sélectionnés. Commandez en ligne et récupérez votre repas au 236 rue d’Ornano.')),
                ('address', models.CharField(default='236 rue d’Ornano, 33000 Bordeaux', max_length=240)),
                ('telephone', models.CharField(default='05 56 42 14 49', max_length=40)),
                ('public_email', models.EmailField(blank=True, max_length=254)),
                ('google_maps_url', models.URLField(default="https://maps.google.com/?q=Pizza+Vitti+236+Rue+d'Ornano+33000+Bordeaux")),
                ('google_review_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('facebook_url', models.URLField(blank=True)),
                ('uber_eats_url', models.URLField(blank=True)),
                ('deliveroo_url', models.URLField(blank=True)),
                ('just_eat_url', models.URLField(blank=True)),
                ('google_play_url', models.URLField(blank=True)),
                ('legal_company_name', models.CharField(blank=True, max_length=180)),
                ('legal_form', models.CharField(blank=True, max_length=120)),
                ('legal_capital', models.CharField(blank=True, max_length=80)),
                ('legal_registration', models.CharField(blank=True, max_length=180)),
                ('legal_vat_number', models.CharField(blank=True, max_length=80)),
                ('legal_director', models.CharField(blank=True, max_length=180)),
                ('legal_host', models.TextField(blank=True, help_text='Nom et coordonnées vérifiés de l’hébergeur.')),
                ('legal_mediator', models.TextField(blank=True, help_text='Coordonnées vérifiées du médiateur de la consommation.')),
            ],
            options={
                'verbose_name': 'Configuration du site',
                'verbose_name_plural': 'Configuration du site',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='accepted_terms',
            field=models.BooleanField(default=False, verbose_name='CGV acceptées'),
        ),
        migrations.AddField(
            model_name='order',
            name='collection_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de retrait'),
        ),
        migrations.AddField(
            model_name='order',
            name='collection_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de retrait'),
        ),
        migrations.AddField(
            model_name='product',
            name='allergens',
            field=models.CharField(blank=True, help_text='Ex. gluten, lait, œufs. Laissez vide si non renseigné.', max_length=240),
        ),
        migrations.AddField(
            model_name='product',
            name='is_signature',
            field=models.BooleanField(default=False, verbose_name='Signature'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_spicy',
            field=models.BooleanField(default=False, verbose_name='Épicé'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_vegetarian',
            field=models.BooleanField(default=False, verbose_name='Végétarien'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('new', 'En attente'), ('confirmed', 'Confirmée'), ('refused', 'Refusée'), ('cancelled', 'Annulée')], default='new', max_length=20),
        ),
        migrations.CreateModel(
            name='OpeningPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('weekday', models.PositiveSmallIntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')])),
                ('opens_at', models.TimeField(verbose_name='Ouverture')),
                ('closes_at', models.TimeField(verbose_name='Fermeture')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Période d’ouverture',
                'verbose_name_plural': 'Horaires d’ouverture',
                'ordering': ['weekday', 'opens_at'],
                'constraints': [models.UniqueConstraint(fields=('weekday', 'opens_at', 'closes_at'), name='unique_opening_period')],
            },
        ),
        migrations.RunPython(seed_verified_restaurant_operations, migrations.RunPython.noop),
    ]
