# Generated by Django 5.1.4 on 2026-07-27 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_restaurant_operations'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='source_url',
            field=models.URLField(blank=True, help_text='Lien vérifiable vers la source de l’avis.'),
        ),
    ]
