# Generated by Django 5.1.4 on 2026-07-28 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_margherita_3d_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='static_image_path',
            field=models.CharField(blank=True, help_text='Image locale par défaut, par exemple /static/shop/img/drinks/cafe.webp.', max_length=240),
        ),
        migrations.AddField(
            model_name='product',
            name='bottle_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Prix bouteille'),
        ),
        migrations.AddField(
            model_name='product',
            name='glass_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Prix au verre'),
        ),
        migrations.AddField(
            model_name='product',
            name='grape_variety',
            field=models.CharField(blank=True, max_length=120, verbose_name='Cépage'),
        ),
        migrations.AddField(
            model_name='product',
            name='region',
            field=models.CharField(blank=True, max_length=100, verbose_name='Région / origine'),
        ),
        migrations.AddField(
            model_name='product',
            name='vintage',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Millésime'),
        ),
        migrations.AddField(
            model_name='product',
            name='wine_colour',
            field=models.CharField(blank=True, max_length=40, verbose_name='Couleur du vin'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='drinks_banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Bannière de la page boissons'),
        ),
    ]
