# Generated by Django 5.1.4 on 2026-07-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_category_static_image_path_product_bottle_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteconfiguration',
            name='antipasti_banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Photo des entrées et antipasti'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='bambino_banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Photo du menu bambino'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='desserts_banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Photo des douceurs'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='pastas_banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Photo des pâtes'),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='pizzas_banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/', verbose_name='Photo des pizzas'),
        ),
    ]
