# Generated by Django 5.1.4 on 2026-08-06 14:57

from decimal import Decimal
from django.db import migrations, models


def create_local_pages(apps, schema_editor):
    LocalSEOPage = apps.get_model('shop', 'LocalSEOPage')
    pages = [
        ('Pizzeria à Bordeaux', 'pizzeria-bordeaux', 'Une adresse italienne au 236 rue d’Ornano, au cœur de Bordeaux.', 'Pizza Vitti accueille les Bordelais pour déguster des pizzas, pastas et desserts italiens sur place ou à emporter. Le restaurant se trouve uniquement à Bordeaux, rue d’Ornano.', 'Pizzeria à Bordeaux | Pizza Vitti rue d’Ornano', 'Découvrez Pizza Vitti, pizzeria italienne au 236 rue d’Ornano à Bordeaux : menu sur place, à emporter et réservation.'),
        ('Pizza italienne à Bordeaux', 'pizza-italienne-bordeaux', 'Découvrez la carte de pizzas de Pizza Vitti à Bordeaux.', 'Notre carte réunit plusieurs recettes italiennes, dont la Margherita, la Regina et des options végétariennes. Consultez les ingrédients et disponibilités directement sur le menu.', 'Pizza italienne à Bordeaux | Pizza Vitti', 'Consultez les pizzas italiennes de Pizza Vitti à Bordeaux, disponibles sur place ou à emporter rue d’Ornano.'),
        ('Restaurant italien à Bordeaux', 'restaurant-italien-bordeaux', 'Pizzas, pastas, entrées et desserts italiens à Bordeaux.', 'Pizza Vitti est situé au 236 rue d’Ornano à Bordeaux. Retrouvez la carte actuelle, les horaires et la réservation sur ce site officiel.', 'Restaurant italien à Bordeaux | Pizza Vitti', 'Pizza Vitti, restaurant italien à Bordeaux : pizzas, pastas et desserts sur place ou à emporter.'),
        ('Pizza à emporter à Bordeaux', 'pizza-a-emporter-bordeaux', 'Commandez votre pizza puis retirez-la chez Pizza Vitti.', 'Le retrait s’effectue au restaurant, 236 rue d’Ornano à Bordeaux. La disponibilité des produits est indiquée dans le menu en ligne.', 'Pizza à emporter Bordeaux | Pizza Vitti', 'Commandez une pizza à emporter chez Pizza Vitti et retirez-la au 236 rue d’Ornano à Bordeaux.'),
        ('Pizzeria rue d’Ornano', 'pizzeria-rue-d-ornano', 'Pizza Vitti vous accueille au 236 rue d’Ornano à Bordeaux.', 'Consultez le menu, réservez une table ou préparez un retrait au restaurant. L’itinéraire officiel est accessible depuis cette page.', 'Pizzeria rue d’Ornano Bordeaux | Pizza Vitti', 'Trouvez Pizza Vitti au 236 rue d’Ornano à Bordeaux : menu, réservation, horaires et itinéraire.'),
        ('Pizza près de Mériadeck', 'pizza-pres-de-meriadeck', 'Depuis Mériadeck, rejoignez Pizza Vitti rue d’Ornano à Bordeaux.', 'Pizza Vitti n’a pas de succursale à Mériadeck : le restaurant se situe au 236 rue d’Ornano. Vérifiez l’itinéraire et les horaires avant votre visite.', 'Pizza près de Mériadeck | Pizza Vitti Bordeaux', 'Depuis Mériadeck, découvrez Pizza Vitti au 236 rue d’Ornano à Bordeaux, avec menu et itinéraire.'),
        ('Pizza près du CHU de Bordeaux', 'pizza-pres-du-chu-bordeaux', 'Pizza Vitti est accessible depuis le secteur du CHU de Bordeaux.', 'Notre unique restaurant se trouve au 236 rue d’Ornano à Bordeaux. Consultez le menu et l’itinéraire pour organiser votre venue ou votre retrait.', 'Pizza près du CHU Bordeaux | Pizza Vitti', 'Depuis le CHU de Bordeaux, retrouvez Pizza Vitti rue d’Ornano : menu, réservation et itinéraire.'),
        ('Pizza végétarienne à Bordeaux', 'pizza-vegetarienne-bordeaux', 'Retrouvez les produits signalés comme végétariens sur le menu Pizza Vitti.', 'Les badges du menu identifient les recettes enregistrées comme végétariennes. Consultez la fiche de chaque produit pour connaître sa description et ses allergènes déclarés.', 'Pizza végétarienne Bordeaux | Pizza Vitti', 'Découvrez les pizzas indiquées végétariennes chez Pizza Vitti à Bordeaux et consultez leurs ingrédients déclarés.'),
    ]
    for title, slug, introduction, body, meta_title, meta_description in pages:
        LocalSEOPage.objects.get_or_create(slug=slug, defaults={
            'title': title, 'introduction': introduction, 'body': body,
            'meta_title': meta_title, 'meta_description': meta_description,
            'faq_question': 'Où se trouve Pizza Vitti ?',
            'faq_answer': 'Pizza Vitti se trouve au 236 rue d’Ornano, 33000 Bordeaux.',
            'is_published': True,
        })


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0027_activate_default_loyalty_reward'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalSEOPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=180)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('introduction', models.TextField()),
                ('body', models.TextField()),
                ('meta_title', models.CharField(max_length=70)),
                ('meta_description', models.CharField(max_length=160)),
                ('faq_question', models.CharField(blank=True, max_length=240)),
                ('faq_answer', models.TextField(blank=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Page SEO locale',
                'verbose_name_plural': 'Pages SEO locales',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='accepted_payments',
            field=models.CharField(default='Cash, Visa, Mastercard, CB, Contactless', max_length=240),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='city',
            field=models.CharField(default='Bordeaux', max_length=100),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='country_code',
            field=models.CharField(default='FR', max_length=2),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='cuisine_types',
            field=models.CharField(default='Italian, Pizza', max_length=180),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='google_business_profile_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='latitude',
            field=models.DecimalField(decimal_places=7, default=Decimal('44.8324494'), max_digits=10),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='longitude',
            field=models.DecimalField(decimal_places=7, default=Decimal('-0.5944067'), max_digits=10),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='postal_code',
            field=models.CharField(default='33000', max_length=20),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='price_range',
            field=models.CharField(default='€€', max_length=20),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='street_address',
            field=models.CharField(default='236 rue d’Ornano', max_length=180),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='tiktok_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='siteconfiguration',
            name='youtube_url',
            field=models.URLField(blank=True),
        ),
        migrations.RunPython(create_local_pages, migrations.RunPython.noop),
    ]
