# Generated by Django 5.1.4 on 2026-08-06 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_localseopage_siteconfiguration_accepted_payments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_alt',
            field=models.CharField(blank=True, help_text='Description accessible de la photo. Un texte est généré si ce champ reste vide.', max_length=180),
        ),
        migrations.AddField(
            model_name='product',
            name='image_title',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='product',
            name='ingredients',
            field=models.TextField(blank=True, help_text='Ingrédients vérifiés uniquement. Ne pas ajouter de revendication non confirmée.'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_indexable',
            field=models.BooleanField(default=True, verbose_name='Autoriser l’indexation SEO'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_published',
            field=models.BooleanField(default=True, verbose_name='Publié sur le site'),
        ),
    ]
